const THEME = {
    LIGHT: {
        backgroundColorUnit: '#004044',
        backGroundTransparent: '#ffffff',
        backGroundColorItem: '#ffffff',
        textColorItem: '#000',

        // Footer
        textColorFooter: '#a5a5a5',
        likeFooter: '#393939',

        // chưa dùng
        backGroundColorFeed: '#e8eaed',
        backGroundColorMessenger: '#dddfe2',
        titleColor: '#000',
        textTabColor: '#2a2a2a',
        backGroundColorListHeader: '#dddfe2',
        colorIconBackForward: '#cfd0d2',
        colorNameCompany: '#000',
        textAppColor: '#000',
        lunarColor: '#9E9E9E',
        calendarColor: '#4C4F95',
        calendarColorText: '#000',
        colorWeather: '#4C4F95',
        colorOption: '#999999',
        colorTimeEntry: '#65676a',
        colorAudience: '#a3a3a3',
        colorIconLikeCmt: '#616770',
        backGroundTab: '#fff',
        backGroundAppHeader: '#fff',
        colorIconTab: '#5B5B5B',
        backGroundFeedCalendar: '#e8eaed',
        colorIconCalendar: '#757575',
        colorTextAppList: '#757575',
        backGroundHeaderApp: '#fff',
        backGroundTabBottom: '#fff',
        backGroundCommentInput: '#fff',
        backGroundBackToTop: '#b1b1b1',
        backGroundIconActive: '#3f51b5',
        backGroundHeaderRight: '#fff',
        colorIconFind: '#3578E5',
    },
    DARK: {
        backgroundColorUnit: '#272729',
        backGroundTransparent: '#fafafa',
        backGroundColorItem: '#272729',
        textColorItem: '#fff',

        // Footer
        textColorFooter: '#fff',
        likeFooter: '#535353',

        // chưa dùng
        backGroundColorFeed: '#ffffff00',
        backGroundColorMessenger: '#ffffff00',
        titleColor: '#fff',
        textTabColor: '#fff',
        backGroundColorListHeader: '#e7e9ec',
        colorIconBackForward: '#fff',
        colorNameCompany: '#fff',
        textAppColor: '#fff',
        lunarColor: '#fff',
        calendarColor: '#fff',
        calendarColorText: '#fff',
        colorWeather: '#fff',
        colorOption: '#fff',
        colorTimeEntry: '#fff',
        colorAudience: '#fff',
        colorIconLikeCmt: '#fff',
        backGroundTab: '#072f5b',
        backGroundAppHeader: '#072f5b',
        colorIconTab: '#fff',
        backGroundFeedCalendar: '#ffffff00',
        colorIconCalendar: '#fff',
        colorTextAppList: '#fff',
        backGroundHeaderApp: '#0a4789',
        backGroundTabBottom: '#072f5b',
        backGroundCommentInput: '#038CF5',
        backGroundBackToTop: '#038CF5',
        backGroundIconActive: '#038CF5',
        backGroundHeaderRight: '#00000056',
        colorIconFind: '#3578E5',
    },
};
export default THEME;
